# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod mokten/StubPlay

  target 'Example-iOSTests' do
    inherit! :search_paths

  end

end
