source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'
use_frameworks!

target 'Example-iOS' do
  use_frameworks!

 pod 'StubPlay'

  target 'Example-iOSTests' do
    inherit! :search_paths

  end

end
